### ISSUE TITLE
How to set up textures?

### ISSUE THREAD

**Issue by PrinceWizardWolf** [TiredHobgoblin/Destiny-Collada-Generator#9]
It's probably me, but I go into blender. Then I import the .dae file, so...

If I need to add the textures myself what needs to connect with what...

If it's supposed add the textures itself, what did I do wrong?

**Comment by TiredHobgoblin** [comment]
Textures need to be set up manually, since the materials are too complex to put into a Collada file. If you join the [Destiny Model Rips Discord server](https://discord.gg/U5eCq4b), we have tutorials on how to use the tool and set up the models.

**Comment by PrinceWizardWolf** [comment]
Ok thank you!
